### ISSUE TITLE
Package as a gem

### ISSUE THREAD

**Issue by danp** [obfuscurity/tasseo#5]
It would be really cool if tasseo was packaged as a gem so it could be run without having to clone/fork the repo. With that option available, here's what I might do to run it on Heroku:

``` bash
$ mkdir dashboards
$ cat <<EOF > dashboards/foo.js
var metrics = { ... }
EOF
$ cat <<EOF > Gemfile
source :rubygems
gem "tasseo"
EOF
$ bundle install
...
$ cat <<EOF > Procfile
web: bundle exec tasseo-web --port $PORT --dashboards dashboards
EOF
$ heroku create -s cedar
$ git push heroku master
```

This way I only need to `bundle update tasseo` or similar to update the app instead of dealing with an entire repo.

**Comment by ebouchut** [comment]
Thanks  @gorsuch and @lgierth.
I would be interested in using it as a Gem, @lgierth do you plan on making a pull-request?
@gorsuch would you accept it ?

**Comment by lgierth** [comment]
Not using tasseo anymore, and not with SoundCloud anymore. Feel free to pick up the changes from the commit I linked above.

**Comment by obfuscurity** [comment]
Sure, I'd be fine with merging in a PR for this.
